extends AnimatedSprite2D


var ammo = 50

const PRECISION = 0.32
const BULLET_DURATION = 0.5
const MIN_BULLET_SPEED = 900
const MAX_BULLET_SPEED = 1000
const COOLDOWN = 0.05
const SHAKE_STRENGTH = 8.0
const MIN_BULLETS = 1
const MAX_BULLETS = 1
const ANIMATION_INCREASE = 2
const ANIMATION_DURATION = 0.08
